### ISSUE TITLE
mining

### ISSUE THREAD

**Issue by wanderer** [ethereum/node-ethereum#1]
Should implement mining

**Comment by wanderer** [comment]
miming is probably broken in node-ethereum at [mining.js](https://github.com/ethereum/node-ethereum/blob/master/lib/mine.js) and in ethereumjs-lib at [runblock.js](https://github.com/ethereum/ethereumjs-lib/blob/master/lib/vm/runBlock.js)

**Comment by kumavis** [comment]
`mine.js` is using an outdated signature for `vm.runBlock`

**Comment by kumavis** [comment]
also
```
╭─{👘 } kumavis in ~/Development/Node/node-ethereum on (develop✱) 
╰─± ./bin/ethereum
XhrRpcServer - opening: /:8080
WebsocketRpcServer - opening: /:40404
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Ssdp.addListener (events.js:160:15)
    at Ssdp.search (/Users/kumavis/Development/Node/node-ethereum/node_modules/nat-upnp/lib/nat-upnp/ssdp.js:79:8)
    at /Users/kumavis/Development/Node/node-ethereum/node_modules/nat-upnp/lib/nat-upnp/ssdp.js:111:23
    at Array.forEach (native)
    at onready (/Users/kumavis/Development/Node/node-ethereum/node_modules/nat-upnp/lib/nat-upnp/ssdp.js:109:19)
    at Socket.<anonymous> (/Users/kumavis/Development/Node/node-ethereum/node_modules/nat-upnp/lib/nat-upnp/ssdp.js:124:7)
    at Socket.g (events.js:180:16)
    at Socket.emit (events.js:95:17)
    at dgram.js:211:14
    at dns.js:72:18
dbServer - started: /:30304
info state starting with state root of: 17e921e481b7ae367764c9100594ca494845f9c352f0a782852d36ad5a30fa3d height:04
ERR! start Error: timeout
ERR! start     at null._onTimeout (/Users/kumavis/Development/Node/node-ethereum/node_modules/nat-upnp/lib/nat-upnp/client.js:178:14)
ERR! start     at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
ERR! start  [Error: timeout]
starting mining!
nonce found!
41 s, 201.484 ms - 
hash/s: 7983.292682926829

/Users/kumavis/Development/Node/node-ethereum/lib/mine.js:46
      self.network.broadcastNewBlock(currentBlock, bignum.fromBuffer(currentBl
                   ^
TypeError: Cannot call method 'broadcastNewBlock' of undefined
    at /Users/kumavis/Development/Node/node-ethereum/lib/mine.js:46:20
    at /Users/kumavis/Development/Node/node-ethereum/node_modules/ethereumjs-lib/lib/block.js:162:7
    at /Users/kumavis/Development/Node/node-ethereum/node_modules/async/lib/async.js:254:17
    at done (/Users/kumavis/Development/Node/node-ethereum/node_modules/async/lib/async.js:135:19)
    at /Users/kumavis/Development/Node/node-ethereum/node_modules/async/lib/async.js:32:16
    at /Users/kumavis/Development/Node/node-ethereum/node_modules/async/lib/async.js:251:21
    at /Users/kumavis/Development/Node/node-ethereum/node_modules/async/lib/async.js:575:34
    at /Users/kumavis/Development/Node/node-ethereum/node_modules/ethereumjs-lib/lib/blockHeader.js:153:7
    at /Users/kumavis/Development/Node/node-ethereum/node_modules/ethereumjs-lib/lib/blockchain.js:189:7
    at Stream.<anonymous> (/Users/kumavis/Development/Node/node-ethereum/node_modules/multilevel/node_modules/rpc-stream/index.js:77:10)
╭─{👘 } kumavis in ~/Development/Node/node-ethereum on (develop✱) 
╰─± 
```
