### ISSUE TITLE
RPC eth_listening throws error

### ISSUE THREAD

**Issue by jorisbontje** [ethereum/node-ethereum#52]
```
TypeError: Cannot read property 'listening' of undefined
    at EthRPC.eth_listening (/Users/mids/Projects/ethereum/vapor/node_modules/node-ethereum/lib/ethRPC.js:167:28)
    at EthRPC.processRpc (/Users/mids/Projects/ethereum/vapor/node_modules/node-ethereum/lib/ethRPC.js:63:6)
    at /Users/mids/Projects/ethereum/vapor/node_modules/node-ethereum/lib/xhrRPC.js:42:11
    at Layer.handle [as handle_request] (/Users/mids/Projects/ethereum/vapor/node_modules/node-ethereum/node_modules/express/lib/router/layer.js:82:5)
    at next (/Users/mids/Projects/ethereum/vapor/node_modules/node-ethereum/node_modules/express/lib/router/route.js:110:13)
    at Route.dispatch (/Users/mids/Projects/ethereum/vapor/node_modules/node-ethereum/node_modules/express/lib/router/route.js:91:3)
    at Layer.handle [as handle_request] (/Users/mids/Projects/ethereum/vapor/node_modules/node-ethereum/node_modules/express/lib/router/layer.js:82:5)
    at /Users/mids/Projects/ethereum/vapor/node_modules/node-ethereum/node_modules/express/lib/router/index.js:267:22
    at Function.proto.process_params (/Users/mids/Projects/ethereum/vapor/node_modules/node-ethereum/node_modules/express/lib/router/index.js:321:12)
    at next (/Users/mids/Projects/ethereum/vapor/node_modules/node-ethereum/node_modules/express/lib/router/index.js:261:10)
```

**Comment by wanderer** [comment]
ok i think i fixed this. So `listening` is returning a bool. Do you know if that is coorect @jorisbontje ?

**Comment by jorisbontje** [comment]
Its no longer giving an error :)
