### ISSUE TITLE
dep name mismatch

### ISSUE THREAD

**Issue by kumavis** [ethereum/node-ethereum#65]
maybe a breaking change without a proper version bump?
```
╭─{🚀 } kumavis in ~/Development/Node/node-ethereum on (rpc✱) 
╰─± bin/nether
module.js:338
    throw err;
          ^
Error: Cannot find module 'ethereumjs-p2p'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/kumavis/Development/Node/node-ethereum/node_modules/ethereumjs-lib/lib/networking.js:1:96)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```

**Comment by wanderer** [comment]
i'm not able to replicate. Have you tried reinstalling?

**Comment by wanderer** [comment]
should be probably bumped now
